apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-nodescaler-sa
  namespace: openshift-ai-nodescaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-nodescaler-role
  namespace: openshift-machine-api
rules:
  - apiGroups: ["machine.openshift.io"]
    resources: ["machinesets"]
    verbs: ["get", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-nodescaler-binding
  namespace: openshift-machine-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ai-nodescaler-role
subjects:
  - kind: ServiceAccount
    name: ai-nodescaler-sa
    namespace: openshift-ai-nodescaler