apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-nodescaler
  namespace: openshift-ai-nodescaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-nodescaler
  template:
    metadata:
      labels:
        app: ai-nodescaler
    spec:
      serviceAccountName: ai-nodescaler-sa
      containers:
        - name: ai-nodescaler
          image: <your-registry>/openshift-ai-nodescaler:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: metrics
          env:
            - name: CHECK_INTERVAL
              value: "60"
            - name: CPU_THRESHOLD
              value: "0.6"
            - name: MEM_THRESHOLD
              value: "0.6"
            - name: NODE_USAGE_LIMIT
              value: "0.5"
            - name: MAX_REPLICAS
              value: "10"
            - name: PROM_URL
              value: "https://prometheus-k8s.openshift-monitoring.svc:9091/api/v1/query"
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            exec:
              command: ["cat", "/tmp/healthy"]
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            exec:
              command: ["cat", "/tmp/healthy"]
            initialDelaySeconds: 15
            periodSeconds: 30